# Generated by Django 5.2.6 on 2025-09-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='stored_name',
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(editable=False),
        ),
    ]
