# Generated by Django 5.2.6 on 2025-10-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_file_stored_name_alter_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='discription',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
