# Generated by Django 5.2.6 on 2025-10-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_file_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='discription',
            new_name='description',
        ),
    ]
