# Generated by Django 5.2.6 on 2025-10-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_rename_discription_file_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='original_name',
            new_name='name',
        ),
    ]
