# Generated by Django 5.2.6 on 2025-12-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_rename_original_name_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
