# Generated by Django 5.2.6 on 2025-12-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_download_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='share_link',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
