# Generated by Django 5.2.6 on 2025-12-08 17:48

from django.db import migrations
import secrets

def fill_share_links(apps, schema_editor):
    File = apps.get_model('storage', 'File')
    for f in File.objects.all():
        f.share_link = secrets.token_urlsafe(32)
        f.save()

class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_file_last_download_at_file_share_link'),
    ]

    operations = [
        migrations.RunPython(fill_share_links),
    ]