# Generated by Django 5.2.6 on 2025-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20251209_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='share_link',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
