# Generated by Django 5.2.6 on 2025-12-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_file_share_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='original_name',
        ),
    ]
